#!/usr/bin/env sh
# Author:       Casey Sparks
# Date:         May 18, 2022.
# Description:  A simple wrapper for xrandr scripts.

HOSTNAME="$(cat /etc/hostname)"

"$HOME"/.env/config/xrandr/"$HOSTNAME"/"$1"                             \
    2> /dev/null                                                        \
    && betterlockscreen                                                 \
        -u "$HOME"/Pictures/backgrounds/"$HOSTNAME".*

command . "$HOME"/.bashrc
