---
- name: 'Filesystem'
  become: true
  tags:
      - 'filesystem'
  block:
      - name: 'Update fstab file with tmpfs /tmp'
        ansible.builtin.lineinfile:
            path: '/etc/fstab'
            regexp: 'tmpfs /tmp tmpfs'
            line: 'tmpfs /tmp tmpfs defaults,lazytime,noatime,nodiratime 0 0'
            state: 'present'
            backup: true
        tags:
            - 'fstab'

      - name: 'Discard trim enable'
        ansible.builtin.systemd:
            name: 'fstrim.timer'
            state: 'started'
            enabled: true
            daemon_reload: true
        tags:
            - 'fstrim'
            - 'systemd'
...
