---
- name: 'Install dependencies'
  become: true
  tags:
      - 'always'
  block:
      - name: 'Install APT packages'
        when: "ansible_os_family == 'Debian'"
        tags:
            - 'apt'
        block:
            - name: 'Update APT cache'
              ansible.builtin.apt:
                  update_cache: true
                  cache_valid_time: 3600
                  name: '*'

            - name: 'Install APT packages'
              ansible.builtin.apt:
                  name: '{{ performance_tweaks_apt_packages }}'

      - name: 'Install DNF packages'
        when: "ansible_os_family == 'RedHat'"
        tags:
            - 'dnf'
        ansible.builtin.dnf:
            name: '{{ performance_tweaks_dnf_packages }}'
            state: 'present'

      - name: 'Install Pacman packages'
        when: "ansible_os_family == 'Archlinux'"
        tags:
            - 'pacman'
        community.general.pacman:
            name: '{{ performance_tweaks_pacman_packages }}'
            state: 'present'
...
