---
- name: 'Load IO Schedulers at boot'
  become: true
  tags:
      - 'io_scheduler'
  ansible.builtin.blockinfile:
      path: '/etc/modules-load.d/iosched.conf'
      create: true
      mode: '0644'
      block: |
          bfq
          mq-deadline
          kyber-iosched
...
