---
- name: 'Run performance tweaks'
  tags:
      - 'performance_tweaks'
      - 'optional'
  ansible.builtin.include_tasks: '{{ item }}.yml'
  loop:
      - 'install_dependencies'
      - 'timeshift'
      - 'io_sched'
      - 'filesystem'
      - 'reflector'
...
