---
- name: 'Run performance tweaks.'
  tags:
      - 'performance_tweaks'
      - 'optional'
  ansible.builtin.include_tasks: '{{ item }}'
  loop:
      - 'install_dependencies.yml'
      - 'timeshift.yml'
      - 'io_sched.yml'
      - 'filesystem.yml'
      - 'reflector.yml'
...
