---
- name: 'Run performance tweaks.'
  tags:
      - 'performance_tweaks'
      - 'optional'
  block:
      - name: 'Install dependencies.'
        ansible.builtin.include_tasks: 'install_dependencies.yml'

      - name: 'Timeshift.'
        ansible.builtin.include_tasks: 'timeshift.yml'

      - name: 'IO scheduer.'
        ansible.builtin.include_tasks: 'io_sched.yml'

      - name: 'Filesystem tweaks.'
        ansible.builtin.include_tasks: 'filesystem.yml'

      - name: 'Reflector.'
        ansible.builtin.include_tasks: 'reflector.yml'
...
