#!/usr/bin/env bash
# docker wrapper.
docker(){
    case "$@" in
        login\ primetrust-security-platform)
            command aws ecr get-login-password --profile security-platform | \
                docker login -u AWS --password-stdin ${DEVOPS_ECR} ;;

        login\ primetrust-security-corporate)
            command aws ecr get-login-password --profile security-corporate | \
                docker login -u AWS --password-stdin ${DEVOPS_ECR} ;;

        login\ caseysparkz)
            command aws ecr get-login-password | \
                docker login -u AWS --password-stdin ${ECR} ;;

        *)
            command docker "$@"
    esac
}
