#!/usr/bin/env bash
# git wrapper.
git(){
    case "$@" in
        gud)
            command git pull && \
                git remote prune origin ;;

        got)
            command git reset --hard HEAD && \
                git clean --force ;;

        rekt)
            command git reset --hard origin/$(git branch --show-current) && \
                git clean --force ;;

        sent)
            command git commit --amend --no-edit && \
                git push --force ;;

        *)
            command git "$@"
    esac
}
