#!/usr/bin/env bash
# pip wrapper.
pip(){
    case "$@" in
        upgrade)
            command pip3 list --outdated --format=freeze | \
                grep -v '^\-e' | \
                cut -d = -f 1 | \
                xargs -n1 pip3 install -U 
        ;;

        *)
            command pip "$@"
    esac
}
