#!/usr/bin/env bash
# podman wrapper.
podman(){
    case "$@" in
        login\ primetrust-security-platform)
            command aws ecr get-login-password --profile security-platform | \
                podman login ${DEVOPS_ECR} -u AWS --password-stdin;;

        login\ primetrust-security-corporate)
            command aws ecr get-login-password --profile security-corporate | \
                podman login ${DEVOPS_ECR} -u AWS --password-stdin;;

        login\ caseysparkz)
            command aws ecr get-login-password | \
                podman login ${ECR} -u AWS --password-stdin;;

        *)
            command podman "$@"
    esac
}
