#!/usr/bin/env bash
# Change directory and clear terminal
cdc() {
  cd $1
  clear
}

# Change directory, clear terminal, and display directory contents as list 
cdl() {
  cd $1
  clear
  ls -l
}

# Make a directory and enter it.
mkcd() {
  mkdir -p ${1} &&
    cd ${1}
}
