#!/usr/bin/env bash
# docker wrapper.
docker(){
    case "$@" in
        login\ primetrust-security-platform)
            command aws ecr get-login-password --profile security-platform | \
                docker login ${DEVOPS_ECR} -u AWS --password-stdin;;

        login\ primetrust-security-corporate)
            command aws ecr get-login-password --profile security-corporate | \
                docker login ${DEVOPS_ECR} -u AWS --password-stdin;;

        login\ caseysparkz)
            command aws ecr get-login-password | \
                docker login ${ECR} -u AWS --password-stdin;;

        *)
            command docker "$@"
    esac
}
