#!/usr/bin/env bash
# Export encrypted environment variables to bash session.
getsecrets() {
    if lsusb | grep --quiet --ignore-case 'yubikey'; then
        for LINE in $(gpg --decrypt ${HOME}/.env/config/bash/secrets.asc 2> /dev/null |
            grep -v "^#"); do
                export ${LINE}
        done
    fi
}
