#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Date:         January 25, 2022
# Description:
'''A simple CLI clock.'''

__author__ = 'Casey Sparks'
__requires__ = []

from argparse import Namespace, ArgumentParser
from datetime import datetime
from locale import setlocale, LC_ALL
from os import system
from time import sleep


setlocale(LC_ALL, 'en_US.UTF-8')


def get_arguments() -> Namespace:
    '''
    Get cmdline arguments.
        :return:    argparse.Namespace instance of user arguments.
    '''
    parser = ArgumentParser(description=__doc__)                            # Instantiate argument parser.

    parser.add_argument(                                                    # 12-hour time.
        '-12',
        action='store_true',
        dest='twelve',
        help='Set format to 12hr time.'
    )

    arguments = parser.parse_args()

    return arguments


if __name__ == '__main__':
    args = get_arguments()
    FSTRING = '%I:%M:%S %p' if args.twelve else '%H:%M:%S'

    while True:
        system('clear')
        print(f'===========\n{datetime.now().strftime(FSTRING)}\n===========')
        sleep(1)
