#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# Date:         February 09, 2022.
# Description:
'''Display information about a network interface.'''

__author__ = 'Casey Sparks'

from argparse import ArgumentParser, Namespace
from fcntl import fcntl
from locale import setlocale, LC_ALL
from logging import getLogger, StreamHandler, DEBUG
from socket import inet_ntoa, socket, SOCK_DGRAM, AF_INET
from struct import pack
from typing import Optional
from requests import get

setlocale(LC_ALL, 'en_US.UTF-8')

log = getLogger()
log.addHandler(StreamHandler())
log.setLevel(DEBUG)


def get_arguments() -> Namespace:
    '''Get cmdline arguments.'''
    parser = ArgumentParser(
        description='Display information about a network interface.'
    )

    parser.add_argument(
        '--interface', '-i',
        dest='interface',
        default=wan_interface()[0],
        help='Specify the network interface.'
    )

    return parser.parse_args()


def public_ip() -> str:
    '''Get our public IP address.'''
    return get('https://ipinfo.io/ip', timeout=2).text


def wan_interface() -> str:
    '''Read the default gateway directly from /proc.'''
    with open('/proc/net/route', 'r', encoding='utf-8') as fh:
        for line in fh:
            fields = line.strip().split()
            if fields[1] == '00000000':
                return fields[0], inet_ntoa(pack('<L', int(fields[2], 16)))


def interface_info(
    iface: str
        ) -> Optional[list]:
    '''
    Get the default gateway.
        :param iface: The network interface to query.
    '''
    with open('/proc/net/route', 'r', encoding='utf-8') as fh:
        for line in fh:
            fields = line.strip().split()
            if fields[0] == iface and fields[7] != '00000000':
                return fields


def local_ip(
    iface: str
        ) -> str:
    '''
    Get the local IP address of an inter.
        :param iface: The network iface to query.
    '''
    file_descriptor = socket(                                               # Get file descriptor.
        AF_INET, SOCK_DGRAM
    ).fileno()
    inet_socket = inet_ntoa(
        fcntl(
            file_descriptor,
            0x8915,                                                         # SIOCGIFADDR
            pack('256s', bytes(iface, 'utf-8'))
        )[20:24]
    )

    return inet_socket


def netmask(
    iface: str
        ) -> str:
    '''
    Read the default gateway directly from /proc.
        :param iface: The network interface to query.
    '''
    return inet_ntoa(pack('<L', int(interface_info(iface)[7], 16)))


if __name__ == '__main__':
    args = get_arguments()
    interface = get_arguments().interface                                   # Get interface from arguments.
    network_table = [                                                       # Instantiate netinfo array.
        ['Network Information', ''],
        ['============================', ''],
        ['Public IP:', public_ip()],
        ['Local IP:', local_ip(interface)],
        ['Netmask:', netmask(args.interface)],
        ['Gateway:', wan_interface()[1]],
        ['Interface:', args.interface]
    ]

    for row in network_table:                                               # Print formatted array.
        print('{: <12} {: >15}'.format(*row))
