#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Date:         September 13, 2022
# Description:
'''
Procedurally generate a name for a sprint.
'''

__author__ = 'Casey Sparks'

from locale import setlocale, LC_ALL
from pathlib import Path
from random import choice
from string import punctuation

setlocale(LC_ALL, 'en_US.UTF-8')                                            # Set locale.


def get_word(
    words: list
        ) -> str:
    '''
    Pull a word from list and format.
        :param words:   A list of words to use in the sprint name.
    '''
    return choice(words).lower().translate(str.maketrans('', '', punctuation))


def create_sprint_name(
    wordfile: Path = Path('/usr/share/dict/words')                          # Installed by `words` package.
        ) -> str:
    '''
    Generate a sprint name from two random words.
        :param wordfile:    Path() object of the word file to use.
    '''
    if not wordfile.exists():                                               # Check file exists.
        return 'Install `words` package.'

    with open(wordfile, 'r', encoding='utf-8') as file:
        words = file.read().splitlines()

    return f'{get_word(words)}-{get_word(words)}'


if __name__ == '__main__':
    print(create_sprint_name())
