#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# Author:       Casey Sparks
# Date:         September 13, 2022
# Description:
'''Procedurally generate a name for a sprint.'''

from locale import setlocale, LC_ALL
from pathlib import Path
from random import choice
from string import punctuation

setlocale(LC_ALL, 'en_US.UTF-8')                                            # Set locale.


def get_word(
    wordlist: list
        ) -> str:
    '''
    Pull a word from list and format.
        :param wordlist:   A list of wordlist to use in the sprint name.
        :return:        A random word.
    '''
    return choice(wordlist).lower().translate(str.maketrans('', '', punctuation))


def create_sprint_name(
    wordfile: Path = Path('/usr/share/dict/words')                          # Installed by `words` package.
        ) -> str:
    '''
    Generate a sprint name from two random words.
        :param wordfile:    Path() object of the word file to use.
    '''
    if not wordfile.exists():                                               # Check file exists.
        return 'Install `words` package.'

    with open(wordfile, 'r', encoding='utf-8') as file:
        wordlist = file.read().splitlines()

    return f'{get_word(wordlist)}-{get_word(wordlist)}'


if __name__ == '__main__':
    print(create_sprint_name())
