#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author:       Casey Sparks
# Date:         September 13, 2022
# Description:
'''
Procedurally generate a name for a sprint.
'''

from locale import setlocale, LC_ALL
from os.path import exists
from random import choice

setlocale(LC_ALL, 'en_US.UTF-8')                      # Set locale.

if __name__ == '__main__':
    wordfile = '/usr/share/dict/words'

    if exists(wordfile):
        words = open(wordfile, 'r').read().splitlines()

        print(f'{choice(words)} {choice(words)}')

    else:
        print('Install `words`.')
