#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# Author:       Casey Sparks
# Date:         March 10, 2023
# Description:
'''Parse IPv4 and IPv6 addresses between CIDR and netmask.'''

from argparse import ArgumentParser, Namespace
from ipaddress import ip_network, IPv4Network, IPv6Network
from locale import setlocale, LC_ALL
from math import ceil, log
from sys import exit as sys_exit
from typing import NoReturn

setlocale(LC_ALL, 'en_US.UTF-8')                                            # Set locale.


def get_arguments() -> Namespace:
    '''
    Get cmdline arguments.
        :return:    User-provided commandline arguments.
    '''
    parser = ArgumentParser(description=__doc__)                            # Instantiate argument parser.
    mutex_group = parser.add_mutually_exclusive_group()                     # Create mutex argument group.
    ip_network.__defaults__ = (False,)                                      # Disable strict addressing.

    mutex_group.add_argument(                                               # Addresses/netmasks to process.
        '-a', '--address',
        type=ip_network,
        dest='address',
        help='Subnet to parse, like `192.168.0.1/16`, `10.0.0.1/255.0.0.0`, or `::1`.'
    )
    mutex_group.add_argument(                                               # Number of hosts.
        '-n', '--hosts',
        type=int,
        dest='number_of_hosts',
        help='Get the minimum netmask for a given number of hosts.'
    )
    mutex_group.add_argument(
        '-s', '--size',
        type=str,
        dest='prefix',
        help='Calculate the maximum number of hosts, given a prefix or subnet mask.'
    )

    arguments = parser.parse_args()

    if set(arguments.__dict__.values()) == {None}:
        parser.print_help()
        sys_exit()

    if arguments.number_of_hosts and not 0 < arguments.number_of_hosts <= 2 ** 128:
        parser.error('Number of hosts must be between 1 and 2^128.')

    return arguments


def print_table(
    table_list:  list,
    right_padding: int
        ) -> NoReturn:
    '''
    Create and print a network table.
        :param table_list:      The table to print.
        :param right_padding:   The amount of whitespace padding in the table.
    '''
    for heading, data in table_list:                                        # Print table.
        print(f'{heading:<18}{data:>{right_padding}}')


def get_network_table(
    subnet: (IPv4Network | IPv6Network)
        ) -> (tuple | None):
    '''
    Create and print a network table.
        :param subnet:  The network string to print (like 10.10.10.10/24).
        :return:        The network table.
    '''
    if subnet is None:
        return None

    host_bits = str(subnet).split('/', maxsplit=1)[0]                       # Get host bits.
    div = 34 * '='                                                          # Div length for IPv4 addresses.
    r_pad = 16                                                              # Right padding for IPv4 addresses.
    netmask = 'Netmask'

    if isinstance(subnet, IPv6Network):                                     # Increase div, padding for IPv6 addresses.
        div += 24 * '='
        r_pad += 24
        netmask = 'Prefix'                                                  # IPv6 terminology.

    net_table = [
        [div, ''],
        [f'{subnet}', ''],
        [div.replace('=', '-'), ''],
        ['Host Address', f'{None if host_bits.endswith(".0") else host_bits}'],
        ['Network Address', f'{subnet.network_address}'],
        ['Broadcast Address', f'{subnet.broadcast_address}'],
        ['Hostmask', f'{subnet.hostmask}'],
        [netmask, f'{subnet.netmask}'],
        [f'CIDR {netmask}', f'/{subnet.prefixlen}'],
        ['Version', f'IPv{subnet.version}'],
        ['Private', f'{subnet.is_private}'],
        ['Reserved', f'{subnet.is_reserved}'],
        ['First IP', f'{subnet[0]}'],
        ['Last IP', f'{subnet[-1]}'],
        [div.replace('=', '-'), ''],
        ['Total Addresses', f'{subnet.num_addresses:,}'],
        [div, '']
    ]

    return net_table, r_pad


def get_netmask_table(
    hosts: int
        ) -> (tuple | None):
    '''
    Print the minimum netmask/prefix length for a subnet with a given number of hosts.
        :param hosts:   The maximum number of hosts on the subnet.
        :return:        The netmask table.
    '''
    if hosts is None:
        return None

    div = 57 * '='                                                          # Div length for IPv4 addresses.
    ip6_cidr = f'/{128 - ceil(log(hosts, 2))}'                              # IPv6 CIDR.
    ip6_netmask = str(ip_network(f'::{ip6_cidr}').netmask)                  # IPv6 netmask.
    ip4_cidr = ip4_netmask = '-'                                            # Set default for IPv4.

    if hosts <= 2 ** 32:
        ip4_cidr = f'/{32 - ceil(log(hosts, 2))}'                           # IPv4 CIDR.
        ip4_netmask = str(ip_network(f'0.0.0.0{ip4_cidr}').netmask)         # IPv4 netmask.

    net_table = [
        [div, ''],
        [f'{hosts} Total Addresses', ''],
        [div.replace('=', '-'), ''],
        ['IPv4 CIDR', ip4_cidr],
        ['IPv4 Netmask', ip4_netmask],
        ['IPv6 CIDR', ip6_cidr],
        ['IPv6 Netmask', ip6_netmask],
    ]

    return net_table, 39


def get_max_hosts_table(
    netmask: str
        ) -> int:
    '''
    Calculate the maximum number of hosts for a given subnet mask or prefix length.
        :param netmask: The mask/prefixlen in question.
        :return:        The max-hosts table.
    '''
    def _max_hosts(
        netmask: int,
        max_prefix: int = 32
            ) -> tuple:
        '''
        Calculate the maximum number of hosts for a given netmask and maximum prefix.
        '''
        assert isinstance(netmask, int), '`netmask` must be int.'
        assert netmask <= 128, '`netmask` must be <= 128.'
        assert isinstance(max_prefix, int), '`max_prefix` must be int.'
        assert max_prefix in {32, 128}, '`max_prefix` must be either 32 or 128.'

        return f'{2 ** (max_prefix - int(netmask)):,}' if netmask <= max_prefix else 'Network too large'

    netmask = netmask.lstrip('/')                                           # Remove leading slash if present.

    match netmask.count('.'):                                               # Check if netmask.
        case 3:                                                             # Is netmask.
            netmask = IPv4Network(f'0.0.0.0/{netmask}').prefixlen
        case _:                                                             # Is prefix length.
            pass

    host_table = [                                                          # Hosts table.
        ['Max. IPv4 hosts', _max_hosts(int(netmask), 32)],
        ['Max. IPv6 hosts', _max_hosts(int(netmask), 128)]
    ]

    return host_table, 51


if __name__ == '__main__':
    args = get_arguments()
    if args.address:
        table, padding = get_network_table(args.address)
    elif args.number_of_hosts:
        table, padding = get_netmask_table(args.number_of_hosts)
    elif args.prefix:
        table, padding = get_max_hosts_table(args.prefix)
    else:
        sys_exit(1)

    print_table(table, padding)
