#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# Name:         clock
# Author:       Casey Sparks
# Date:         January 25, 2022
# Description:
'''A simple CLI clock.'''

from argparse import Namespace, ArgumentParser
from datetime import datetime
from locale import setlocale, LC_ALL
from os import system
from sys import exit as sys_exit
from time import sleep
from pytz import utc


setlocale(LC_ALL, 'en_US.UTF-8')


def get_arguments(
    ) -> Namespace:
    '''
    Get cmdline arguments.
        :return:    argparse.Namespace instance of user arguments.
    '''
    parser = ArgumentParser(description=__doc__)                            # Instantiate argument parser.

    parser.add_argument(                                                    # -12
        '-12',
        action='store_true',
        dest='twelve',
        help='Set format to 12hr time.'
        )
    parser.add_argument(                                                    # -12
        '-u', '--utc',
        dest='utc',
        default=True,
        nargs='?',
        type=str,
        help='Run clock in UTC, or pass a %H%M time string to convert to UTC and exit.'
        )

    return parser.parse_args()


def get_utc_time(
    input_time: str = None
    ) -> str:
    '''
    Continuously display a text-based clock.
        :param input_time:         Boolean indicating if clock should show UTC time.
    '''
    assert isinstance(input_time, (str, type(None))), ':param input_time: must be instance of str() or Nonetype.'
    if input_time:
        assert input_time.isdigit(), ':param input_time: must be time string or None.'
        assert int(input_time[:2]) < 24 and int(input_time[2:4]) < 60, ':param input_time: invalid time.'

    localtime = datetime.strptime(input_time, '%H%M') if input_time else datetime.now()

    return localtime.astimezone(utc).strftime('%H%M')


def run_clock(
    twelve_hour: bool = False,
    utc_time: bool = False
    ) -> None:
    '''
    Continuously display a text-based clock.
        :param twelve_hour: Boolean indicating if clock should show twelve-hour time.
        :param utc_time:    Boolean indicating if clock should show UTC time.
    '''
    assert isinstance(twelve_hour, bool), ':param twelve_hour: must be instance of bool().'
    assert isinstance(utc_time, bool), ':param utc_time: must be instance of bool().'

    div = '=' * len((time_string := '%I:%M:%S %p' if twelve_hour else '%H:%M:%S'))

    while True:
        try:
            system('clear')                                                 # Clear screen.

            time = datetime.utcnow() if utc_time else datetime.now()        # UTC or local time.

            print(f'{div}\n{time.strftime(time_string)}\n{div}')            # Print clock.
            sleep(1)                                                        # Sleep one second.

        except KeyboardInterrupt:                                           # Exit without stack trace.
            print()
            sys_exit(1)


if __name__ == '__main__':
    args = get_arguments()
    breakpoint()

    if isinstance(args.utc, (bool, type(None))):                            # Run a clock in the shell.
        run_clock(args.twelve, bool(args.utc))
    elif isinstance(args.utc, str) and len(args.utc) == 4:                  # Run a UTC clock in the shell.
        print(get_utc_time(args.utc))
