#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# Name:         moveit
# Author:       Casey Sparks
# Date:         August 14, 2023
# Description:
'''You know what it do.'''

from locale import setlocale, LC_ALL
from random import randint
from sys import exit as sys_exit
from time import sleep
from pyautogui import moveTo, position

setlocale(LC_ALL, 'en_US.UTF-8')                                            # Set locale.


def user_confirmation() -> bool:
    '''
    Get user confirmation.
        :return:    Boolean indicating manual user confirmation.
    '''
    try:
        return input('Center your cursor and hit <ENTER> to start.\nPress any other key to abort.') == ''

    except KeyboardInterrupt:
        return False


def move_cursor() -> None:
    '''Move the cursor in a 10px square.'''
    start = position()
    x = y = randint(0, 100)                                                 # Random (0-100px) X, Y scalars.

    moveTo(start[0] + x, start[1] + y)
    sleep(1)
    moveTo(start[0], start[1])


if __name__ == '__main__':
    if user_confirmation():
        print('Move it, move it.')

        while True:
            try:
                move_cursor()
                sleep(5)
            except KeyboardInterrupt:
                print('\nExiting.')
                sys_exit(0)
    else:
        print('\nExiting.')
        sys_exit(0)
