#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# Name:         moveit
# Author:       Casey Sparks
# Date:         August 14, 2023
# Description:
'''You know what it do.'''

from locale import setlocale, LC_ALL
from random import randint
from sys import exit as sys_exit
from time import sleep
from pyautogui import FailSafeException, moveTo, position, size

setlocale(LC_ALL, 'en_US.UTF-8')                                                # Set locale.

START_X = size().width / 2                                                      # Horizontal center.
START_Y = size().height / 2                                                     # Vertical center.


def user_confirmation() -> bool:
    '''
    Get user confirmation.
        :return:    Boolean indicating manual user confirmation.
    '''
    try:
        return input('Press <ENTER> to start.\nPress any other key to abort.') == ''

    except KeyboardInterrupt:
        return False


def move_cursor(
    interval: int = 3,
        ) -> None:
    '''
    Move the cursor in a 10px square.
        :param interval:    Interval on which to move the cursor.
    '''
    sleep(interval)
    moveTo(START_X, START_Y)                                                    # Center the cursor.
    sleep(interval)
    moveTo(START_X + randint(0,100), START_Y + randint(0,100))                  # Move random vector.


if __name__ == '__main__':
    if user_confirmation():
        print('Move it, move it.')

        while True:
            try:
                move_cursor()
            except KeyboardInterrupt:
                print('\nExiting.')
                sys_exit(0)
    else:
        print('\nExiting.')
        sys_exit(0)
