---
- name: 'Install distro packages.'
  become: true
  block:
      - name: 'Update APT cache.'
        when: ansible_os_family == 'Debian'
        tags:
            - 'apt'
        ansible.builtin.apt:
            update_cache: true
            cache_valid_time: 3600
            name: '*'

      - name: 'Install APT packages.'
        when: ansible_os_family == 'Debian'
        tags:
            - 'apt'
        ansible.builtin.apt:
            name: '{{ packages_apt }}'

      - name: 'Install former snap packages.'
        when: ansible_os_family == 'Ubuntu'
        loop: '{{ packages_snap_to_apt }}'
        tags:
            - 'apt'
        ansible.builtin.apt:
            name: '{{ item.name }}'

      - name: 'Install DNF packages.'
        tags:
            - 'dnf'
        when: ansible_os_family == 'RedHat'
        ansible.builtin.dnf:
            name: '{{ packages_dnf }}'
            state: 'present'

      - name: 'Install Pacman packages.'
        tags:
            - 'pacman'
        when: ansible_os_family == 'Archlinux'
        community.general.pacman:
            name: '{{ packages_pacman }}'
            state: 'present'

- name: 'Install PIP packages.'
  tags:
      - 'pip'
  ansible.builtin.pip:
      name: '{{ packages_pip }}'
...
