---
- name: '[system_packages]'
  ansible.builtin.include_tasks: 'system_packages.yml'

- name: '[system_services]'
  ansible.builtin.include_tasks: 'system_services.yml'

- name: '[usermod]'
  ansible.builtin.include_tasks: 'usermod.yml'
...
