---
- name: 'Disable and uninstall Snap.'
  become: true
  when: ansible_distribution == 'Ubuntu'
  tags:
      - 'snap'
  block:
      - name: 'Collect system service facts.'
        ansible.builtin.service_facts:
        register: services_state

      - name: 'Stop snapd.'
        ansible.builtin.systemd:
            name: 'snapd.service'
            state: 'stopped'
        when: "'snapd.service' in services_state.ansible_facts.services"

      - name: 'Mask snapd.'
        ansible.builtin.systemd:
            name: 'snapd'
            masked: true

      - name: 'Uninstall snapd.'
        ansible.builtin.apt:
            name: 'snapd'
            state: 'absent'
            purge: true
            autoclean: true
            autoremove: true
            force: true

      - name: 'Hold snapd in apt.'
        ansible.builtin.dpkg_selections:
            name: 'snapd'
            selection: 'hold'
...
