---
- name: 'Add ansible_user to groups.'
  become: true
  tags:
      - 'usermod'
      - 'groupadd'
  block:
      - name: 'Create system groups.'
        ansible.builtin.group:
            name: '{{ item }}'
            state: 'present'
            system: true
        loop:
            - 'docker'

      - name: 'Add ansible_user to groups.'
        ansible.builtin.user:
            name: '{{ ansible_user_id }}'
            groups: '{{ item }}'
            append: true
        loop:
            - 'docker'
...
