---
- name: '[usermod] Add ansible_user to groups'
  become: true
  tags: ['usermod']
  block:
    - name: '[usermod.groups] Create system groups'
      loop: ['docker']
      ansible.builtin.group:
        name: '{{ item }}'
        state: 'present'
        system: true

    - name: '[usermod.user] Add ansible_user to groups'
      loop: ['docker']
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        groups: '{{ item }}'
        append: true
...
