---
- name: '[packages.usermod]'
  become: true
  tags: ['usermod']
  block:
      - name: '[packages.usermod] Create system groups'
        loop:
            - 'docker'
        ansible.builtin.group:
            name: '{{ item }}'
            state: 'present'
            system: true

      - name: '[packages.usermod] Add ansible_user to groups'
        loop:
            - 'docker'
        ansible.builtin.user:
            name: '{{ ansible_user_id }}'
            groups: '{{ item }}'
            append: true
...
