---
- name: '[environment.cron]'
  tags: ['cron']
  block:
      - name: '[environment.cron] Delete screenshots'
        ansible.builtin.cron:
            name: 'Delete screenshots.'
            minute: 0
            hour: 10
            job: 'rm ${HOME}/Pictures/{S,s}creenshots/*'
...
