---
- name: 'Dotfiles'
  tags:
      - 'dotfiles'
  block:
      - name: 'Create ~/.config/ subdirectories'
        loop: '{{ environment_dotfiles.subdirectories }}'
        ansible.builtin.file:
            path: '{{ item.path }}'
            owner: '{{ item.owner }}'
            group: '{{ item.group }}'
            mode: '{{ item.mode }}'
            state: 'directory'

      - name: 'Symlink configuration files'
        loop: '{{ environment_dotfiles.symlinks }}'
        ansible.builtin.file:
            src: '{{ item.src }}'
            dest: '{{ item.dest }}'
            owner: '{{ item.owner }}'
            group: '{{ item.group }}'
            state: 'link'
            force: true
...
