---
- name: '[environment.dotfiles]'
  tags: ['dotfiles']
  block:
      - name: '[environment.dotfiles] Create ~/.config/ subdirectories'
        loop: '{{ environment_dotfiles.subdirectories }}'
        ansible.builtin.file:
            path: '{{ item.path }}'
            owner: '{{ ansible_effective_user_id }}'
            group: '{{ ansible_effective_group_id }}'
            mode: '{{ item.mode }}'
            state: 'directory'

      - name: '[environment.dotfiles] Symlink configuration files'
        loop: '{{ environment_dotfiles.symlinks }}'
        ansible.builtin.file:
            src: '{{ item.src }}'
            dest: '{{ item.dest }}'
            owner: '{{ ansible_effective_user_id }}'
            group: '{{ ansible_effective_group_id }}'
            state: 'link'
            force: true
...
