---
- name: '[environment.filesystem] Create subdirectories in user home'
  tags: ['filesystem']
  loop:
      - 'Documents/git/'
      - 'Pictures/backgrounds/'
      - 'Pictures/screenshots/'
  ansible.builtin.file:
      path: '{{ ansible_env.HOME }}/{{ item }}'
      state: 'directory'
      owner: '{{ ansible_effective_user_id }}'
      group: '{{ ansible_effective_group_id }}'
      mode: '0700'
...
