---
- name: 'Create subdirectories in user home'
  ansible.builtin.file:
      path: '{{ ansible_env.HOME }}/{{ item }}'
      state: 'directory'
      owner: '{{ ansible_user }}'
      group: '{{ ansible_user }}'
      mode: '0700'
  loop:
      - 'Documents/git/'
      - 'Pictures/backgrounds/'
      - 'Pictures/screenshots/'
...
