---
- name: 'GnuPG'
  tags:
      - 'gnupg'
  block:
      - name: 'Create ~/.gnupg/'
        ansible.builtin.file:
            path: '{{ ansible_env.HOME }}/.gnupg'
            state: 'directory'
            owner: '{{ ansible_effective_user_id }}'
            group: '{{ ansible_effective_group_id }}'
            mode: '0700'

      - name: 'Replace ~/.gpg-agent.conf'
        ansible.builtin.copy:
            src: 'gnupg/gpg-agent.conf'
            dest: '{{ ansible_env.HOME }}/.gnupg/gpg-agent.conf'
            owner: '{{ ansible_effective_user_id }}'
            group: '{{ ansible_effective_group_id }}'
            mode: '0600'

      - name: 'Replace ~/.gpg.conf'
        ansible.builtin.copy:
            src: 'gnupg/gpg.conf'
            dest: '{{ ansible_env.HOME }}/.gnupg/gpg.conf'
            owner: '{{ ansible_effective_user_id }}'
            group: '{{ ansible_effective_group_id }}'
            mode: '0600'

      - name: 'Enumerate local PGP pubkeys'
        ansible.builtin.find:
            paths: '{{ role_path }}/files/'
            patterns: '*.asc'
            recurse: false
            file_type: 'file'
        register: 'pgp_pubkeys'

      - name: 'Import PGP keys to user keyring'
        loop: '{{ pgp_pubkeys.files }}'
        ansible.builtin.command:
            cmd: 'gpg --import {{ item.path }}'
        changed_when: false
...
