---
- name: 'Build preferred user environment.'
  tags:
      - 'environment'
  ansible.builtin.include_tasks: '{{ item }}.yml'
  loop:
      - 'bash'
      - 'ca_certificates'
      - 'cron'
      - 'dotfiles'
      - 'filesystem'
      - 'git'
      - 'gnupg'
      - 'python_requirements'
      - 'remove_snap'
      - 'screen'
      - 'script_dir'
      - 'ssh'
      - 'vim'
...
