---
- name: 'Create ~/.config/pylint.'
  ansible.builtin.file:
      path: '{{ ansible_env.HOME }}/.config/pylint'
      state: 'directory'
      owner: '{{ ansible_effective_user_id }}'
      group: '{{ ansible_effective_group_id }}'
      mode: '0755'

- name: 'Symlink pylint.pylintrc'
  ansible.builtin.file:
      src: '{{ role_path }}/files/python/pylint.pylintrc'
      dest: '{{ ansible_env.HOME }}/.config/pylint/pylint.pylintrc'
      state: 'link'
      force: true
      owner: '{{ ansible_effective_user_id }}'
      group: '{{ ansible_effective_group_id }}'
      mode: '0644'
...
