---
- name: 'Remove some annoying default packages'
  become: true
  tags:
      - 'uninstall'
  when: "ansible_os_family == 'Debian'"
  block:
      - name: 'apt'
        loop: '{{ environment_remove_defaults.apt }}'
        tags:
            - 'apt'
        ansible.builtin.apt:
            name: '{{ item }}'
            state: 'absent'
            autoremove: true
            purge: true
            clean: true

      - name: 'dnf'
        loop: '{{ environment_remove_defaults.dnf }}'
        tags:
            - 'dnf'
        ansible.builtin.dnf:
            name: '{{ item }}'
            state: 'absent'
            autoremove: true
...
