---
- name: '[environment.screen] Symlink ~/.screenrc'
  tags: ['screen']
  ansible.builtin.file:
      src: 'screen/screenrc'
      dest: '{{ ansible_env.HOME }}/.screenrc'
      force: true
      state: 'link'
...
