---
- name: 'Symlink ~/.screenrc'
  tags:
      - 'screen'
  ansible.builtin.file:
      src: '{{ role_path }}/files/screen/screenrc'
      dest: '{{ ansible_env.HOME }}/.screenrc'
      force: true
      state: 'link'
...
