---
- name: 'Disable crash reporters'
  become: true
  when: "ansible_distribution == 'Ubuntu'"
  tags:
      - 'whoopsie'
      - 'apport'
      - 'crash_reporters'
  block:
      - name: 'Get package facts'
        ansible.builtin.package_facts:
            manager: 'auto'
        no_log: true

      - name: 'Uninstall whoopsie'
        when: "'whoopsie' in ansible_facts.packages"
        ansible.builtin.apt:
            name: 'whoopsie'
            state: 'absent'
            purge: true

      - name: 'Uninstall whoopsie-preferences'
        when: "'whoopsie-preferences' in ansible_facts.packages"
        ansible.builtin.apt:
            name: 'whoopsie-preferences'
            state: 'absent'
            purge: true

      - name: 'Uninstall Apport'
        when: "'apport' in ansible_facts.packages"
        ansible.builtin.apt:
            name: 'apport'
            state: 'absent'
            purge: true

      - name: 'Remove orphan dependencies'
        ansible.builtin.apt:
            autoremove: true
            autoclean: true
...
