---
- name: 'Install dependencies.'
  tags:
      - 'security'
      - 'firewall'
  block:
      - name: 'Debian'
        when: ansible_os_family == 'Debian'
        become: true
        ansible.builtin.apt:
            name: '{{ item }}'
            state: 'present'
        loop:
            - 'firewalld'
            - 'python3-pip'

      - name: 'Red Hat'
        when: ansible_os_family == 'RedHat'
        become: true
        ansible.builtin.dnf:
            name: '{{ item }}'
            state: 'present'
        loop:
            - 'firewalld'
            - 'python3-pip'

      - name: 'Arch'
        when: ansible_os_family == 'ArchLinux'
        become: true
        community.general.pacman:
            name: '{{ item }}'
            state: 'present'
        loop:
            - 'firewalld'
            - 'python-pip'

      - name: 'Install python3-firewall.'
        ansible.builtin.pip:
            name: 'firewall'

- name: 'Start firewalld service.'
  become: true
  ansible.builtin.systemd:
      name: 'firewalld.service'
      state: 'started'
      enabled: true

- name: 'Block all incoming connections.'
  become: true
  ansible.posix.firewalld:
      state: 'disabled'
      permanent: true
...
