---
- name: 'Iptables'
  become: true
  tags:
      - 'firewall'
      - 'iptables'
  block:
      - name: 'Install iptables packages [APT]'
        when: "ansible_os_family == 'Debian'"
        tags:
            - 'apt'
        loop:
            - 'iptables-persistent'
            - 'netfilter-persistent'
        ansible.builtin.apt:
            name: '{{ item }}'
            state: 'present'

      - name: 'Drop all incoming traffic'
        ansible.builtin.iptables:
            action: 'insert'
            chain: 'INPUT'
            policy: 'DROP'
        notify: 'Restart iptables'
...
