#!/bin/sh
xrandr \
  --output eDP1 --primary --mode 1920x1200 --pos 0x237 --rotate normal \
  --output DP1 --off \
  --output DP2 --off \
  --output DP3 --off \
  --output DP3-1 --mode 1920x1080 --pos 1920x357 --rotate normal \
  --output DP3-2 --mode 1920x1080 --pos 3840x0 --rotate right \
  --output DP3-3 --off \
  --output DP4 --off \
  --output HDMI1 --off \
  --output VIRTUAL1 --off

sleep 2

source ${HOME}/.bashrc
