#!/bin/sh
xrandr \
  --auto

sleep 2

xrandr \
  --output eDP-1 --primary --mode 1920x1080 --pos 0x267 --rotate normal  \
  --output DP-1 --off  \
  --output HDMI-1 --off \
  --output DP-2 --off \
  --output HDMI-2 --off \
  --output DP-1-1 --mode 1920x1080 --pos 3840x0 --rotate right \
  --output DP-1-2 --mode 1920x1080 --pos 1920x267 --rotate normal \
  --output DP-1-3 --off

sleep 2

source ${HOME}/.bashrc
