#!/bin/sh
xrandr \
  --auto

sleep 2

xrandr \
  --output eDP1 --primary --mode 1920x1200 --pos 0x144 --rotate normal \
  --output DP1 --off \
  --output DP2 --off \
  --output DP3 --mode 1920x1080 --pos 3840x0 --rotate right \
  --output DP4 --off \
  --output HDMI1 --mode 1920x1080 --pos 1920x144 --rotate normal \
  --output VIRTUAL1 --off

sleep 2

source ${HOME}/.bashrc
