#!/usr/bin/env bash
if $(lsusb|grep -q 291a:8392); then
    xrandr                      \
        --output eDP-1          \
            --mode 1920x1200    \
            --pos 0x375         \
            --rotate normal     \
        --output HDMI-1 --off   \
        --output DP-1 --off     \
        --output DP-2 --off     \
        --output DP-3 --off     \
        --output DP-4 --off     \
        --output DP-3-1         \
            --primary           \
            --mode 1920x1080    \
            --pos 1920x375      \
            --rotate normal     \
        --output DP-3-2         \
            --mode 1920x1080    \
            --pos 3840x375      \
            --rotate normal     \
        --output DP-3-3 --off
else
    xrandr                      \
        --output eDP-1          \
            --mode 1920x1200    \
            --pos 0x203         \
            --rotate normal     \
        --output HDMI-1 --off   \
        --output DP-1 --off     \
        --output DP-2 --off     \
        --output DP-3 --off     \
        --output DP-4 --off     \
        --output DP-3-1         \
            --primary           \
            --mode 1920x1080    \
            --pos 1920x203      \
            --rotate normal     \
        --output DP-3-2         \
            --mode 1920x1080    \
            --pos 3840x0        \
            --rotate right      \
        --output DP-3-3 --off
fi
