#!/usr/bin/env bash
# Author:       Casey Sparks
# Date:         May 18, 2022.
# Description:  Read QR codes from a screenshot.
# Notes:        Python refactor candidate.

scrot "${TMP_FILE}" -f -s

TMP_FILE='/tmp/scrotscriptout.png'
SCAN_RESULT=$(zbarimg --quiet --raw ${TMP_FILE} | tr -d '\n')

if [ -z "${SCAN_RESULT}" ]; then
    notify-send "scrot" "No scan data found"
else
    echo "${SCAN_RESULT}" | xsel -ib
    convert ${TMP_FILE} -resize 75x75 ${TMP_FILE}
    notify-send -i ${TMP_FILE} "QR Code Scanned:" "${SCAN_RESULT}"
fi

rm ${TMP_FILE}
