#!/usr/bin/env bash
# -*- coding:utf-8 -*-

# Author:       Casey Sparks
# Date:         May 18, 2022
# Description:  Renames all files of a given extension in a directory to a
#               number sequence starting with a given number.

printf "Start numbering at:\n"
read -r START

printf "File extension:\n"
read -r FILETYPE

for FILE in *"${FILETYPE}"; do
  NEW=$(printf "%02d$FILETYPE" "$START")
  mv -i -- "$FILE" "$NEW"
  (( START=START+1 ))
done
