#!/usr/bin/env bash
# -*- coding:utf-8 -*-

# Author:       Casey Sparks
# Date:         May 18, 2022.
# Description:  A simple wrapper for xrandr scripts.

${HOME}/.env/config/xrandr/${HOSTNAME}/${@}                     \
    2> /dev/null                                                \
    && betterlockscreen                                         \
        -u ${HOME}/Pictures/backgrounds/${HOSTNAME}.{jp*g,png}  &

command source ${HOME}/.bashrc
