#!/usr/bin/env bash
# -*- coding:utf-8 -*-

# Author:       Casey Sparks
# Date:         May 18, 2022
# Description:  Simple script to bring up/down Wireguard and check its status.

case $1 in
  up | on)
    sudo wg-quick up wg0 ;;
  down | off)
    sudo wg-quick down wg0 ;;
  *)
    sudo wg
esac
