#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author:       Casey Sparks
# Date:
# Description:

import argparse
import locale
import logging

# Set locale.
locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')

# Log to the screen.
handler = logging.StreamHandler()
log = logging.getLogger()
parser = argparse.ArgumentParser()
args = get_arguments(parser)

handler.setFormatter(logging.Formatter('%(asctime)s: "%(name)s" (line: %(lineno)d) - %(levelname)s %(message)s'))
log.setLevel(logging.DEBUG)
log.addHandler(handler)

def get_arguments(parser):
    parser.add_argument(
        '--verbose', '-v',
        action = 'store_const',
        dest = 'loglevel',
        const = log.DEBUG,
        help = 'Set log level to DEBUG.'
    )
    
    return parser.parse_args()
