#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author:       Casey Sparks
# Date:
# Description:
'''
The `help()` description of the script goes here.
'''

import argparse
import locale
import logging

# Enable logging, set locale, set args.
handler = logging.StreamHandler()
log = logging.getLogger()
parser = argparse.ArgumentParser(
    description=''
)

handler.setFormatter(logging.Formatter(
    '%(asctime)s: %(name)s | %(lineno)d - %(levelname)s %(message)s'
))
locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
logging.basicConfig(
    filename=f'./{__name__}.log'
)
log.addHandler(handler)
log.setLevel(logging.DEBUG)


def get_arguments(parser) -> argparse.Namespace:
    '''Get cmdline arguments.'''
    parser.add_argument(                                        # Enable DEBUG logging.
        '--verbose', '-v',
        action='store_const',
        dest='loglevel',
        const=logging.DEBUG,
        help='Set log level to DEBUG.'
    )

    return parser.parse_args()


if __name__ == '__main__':
    args = get_arguments(parser)                                # Get cmdline arguments.
