#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author:       Casey Sparks
# Date:         
# Description:
'''
The description of the script goes here.                        # EDIT.
'''

import argparse
import locale
import logging

# Enable logging, set locale.
log = logging.getLogger()

locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
log.addHandler(logging.StreamHandler())
log.setLevel(logging.INFO)


def get_arguments() -> argparse.Namespace:
    '''Get cmdline arguments.'''
    parser = argparse.ArgumentParser(                           # EDIT.
        description='The `help()` description of the application goes here.'
    )
    parser.add_argument(                                        # Enable DEBUG logging.
        '--verbose', '-v',
        action='store_const',
        dest='loglevel',
        const=logging.DEBUG,
        help='Set log level to DEBUG.'
    )

    args = parser.parse_args()

    if args.loglevel:                                           # Set debug output.
        log.setLevel(args.loglevel)

    return parser.parse_args()


if __name__ == '__main__':
    args = get_arguments()                                      # Get cmdline arguments.
