---
- name: 'Restart/enable fail2ban.service'
  become: true
  tags:
      - 'fail2ban'
      - 'systemd'
  ansible.builtin.systemd_service:
      name: 'fail2ban.service'
      state: 'started'
      enabled: true
      daemon_reload: true
...
