#!/usr/bin/env bash

alias tmp_file="mktemp -t scrotscript-XXXXXX"
scrot "$tmp_file" -f -s

scanresult=$(zbarimg --quiet --raw "$tmp_file" | tr -d '\n')

if [ -z "$scanresult" ]; then
    notify-send "scrot" "No scan data found"
else
    echo "$scanresult" | clip
    convert $tmp_file -resize 75x75 "$tmp_file"
    notify-send -i "$tmp_file" "scrot" "$scanresult\n(copied to clipboard)"
fi

rm "$tmp_file"
