#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author:       Casey Sparks
# Date:         January 25, 2022
# Description:
'''
whois for IP locations.
'''

import locale
import logging
import os
import sys
import requests

# Enable logging, set locale, set args.
log = logging.getLogger()

locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
log.addHandler(logging.StreamHandler())
log.setLevel(logging.WARN)


if __name__ == '__main__':
    api_key = os.environ.get('IPSTACK_API_KEY')

    if api_key is None:
        log.critical('No API key.')
    else:
        for ip in sys.argv[1:]:
            ip_info = requests.get(
                f'http://api.ipstack.com/{ip}',
                params={'access_key': os.environ.get('IPSTACK_API_KEY')}
            ).json()

            location_table = [
                ['IP:', ip_info["ip"]],
                ['City:', ip_info["city"]],
                ['Region:', ip_info["region_name"]],
                ['ZIP:', ip_info["zip"]],
                ['Country:', ip_info["country_name"]],
                ['Coordinates:', f'{ip_info["latitude"]}, {ip_info["longitude"]}']
            ]

            for row in location_table:
                print('{: <16} {: >0}'.format(*row))
