---
- name: '[common.performance.install_dependencies]'
  become: true
  tags: ['install_dependencies']
  block:
      - name: '[common.performance.install_dependencies] Install'
        when: "ansible_os_family == 'Debian'"
        tags: ['apt']
        ansible.builtin.apt:
            name: '{{ performance_apt_packages }}'
            state: 'present'
            update_cache: true
            cache_valid_time: 3600

      - name: '[common.performance.install_dependencies] Install'
        when: "ansible_os_family == 'RedHat'"
        tags: ['dnf']
        ansible.builtin.dnf:
            name: '{{ performance_dnf_packages }}'
            state: 'present'

      - name: '[common.performance.install_dependencies] Install'
        when: "ansible_os_family == 'Archlinux'"
        tags: ['pacman']
        community.general.pacman:
            name: '{{ performance_pacman_packages }}'
            state: 'present'
...
