---
- name: 'Start systemd services'
  loop: '{{ packages.systemd.services }}'
  ansible.builtin.systemd:
      name: '{{ item }}'
      enabled: true
      state: 'started'

- name: 'Start systemd timers'
  loop: '{{ packages.systemd.timers }}'
  ansible.builtin.systemd:
      name: '{{ item }}'
      enabled: true
      state: 'started'

- name: 'Reload systemd configs'
  become: true
  ansible.builtin.systemd:
      daemon_reload: true
...
