---
name: 'Validate shell code'
on:
    push:
        branches:
            - 'main'
            - 'WIP**'
        paths: 'roles/environment/files/scripts/sh/**'
    pull_request:
        branches:
            - 'main'
        paths: 'roles/environment/files/scripts/sh/**'
jobs:
    shellcheck:
        runs-on: 'ubuntu-latest'
        steps:
            - uses: 'actions/checkout@v3'
            - name: 'Install dependencies'
              run: >
                  sudo apt update
                  && sudo apt install -y shellcheck

            - name: 'Lint shell scripts with Shellcheck'
              run: 'shellcheck ./*'
              working-directory: 'roles/environment/files/scripts/sh/'
...
